name: Chrome++64

on:
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        include: [
          { name: Chrome++_x86, arch: x86 },
          { name: Chrome++_x64, arch: x64 },
        ]

    name: ${{ matrix.name }}

    runs-on: windows-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        submodules: 'true'
    
    - name: Set up Git
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Setup VC-LTL
      run: nuget install VC-LTL

    - name: Setup Xmake
      uses: xmake-io/github-action-setup-xmake@v1

    - name: Configure Xmake
      run: xmake f -a ${{ matrix.arch }}

    - name: Build Chrome++
      run: xmake

    - name: Upload DLL
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.name }}
        path: build/release

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.release.tag_name }}
        release_name: Release ${{ github.event.release.tag_name }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/release
        asset_name: ${{ matrix.name }}.zip
        asset_content_type: application/zip
