name: Build and Release Chrome++

on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    strategy:
      matrix:
        include: [
            { name: Chrome++_x86, arch: x86 },
            { name: Chrome++_x64, arch: x64 },
        ]

    name: ${{ matrix.name }}
    runs-on: windows-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Setup VC-LTL
      run: nuget install VC-LTL

    - name: Setup Xmake
      uses: xmake-io/github-action-setup-xmake@v1

    - name: Configure Xmake
      run: xmake f -a ${{ matrix.arch }}

    - name: Build Chrome++
      run: xmake

    - name: Upload DLL
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.name }}
        path: build/release

    - name: Check for existing release
      id: check_release
      uses: actions/github-script@v6
      with:
        script: |
          const { data: releases } = await github.repos.listReleases({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });
          const release = releases.find(release => release.tag_name === process.env.GITHUB_REF_NAME);
          if (release) {
            core.setOutput("release_exists", true);
          } else {
            core.setOutput("release_exists", false);
          }

    - name: Create Release
      if: steps.check_release.outputs.release_exists == 'false'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      if: steps.check_release.outputs.release_exists == 'false'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/release
        asset_name: chrome_plus_${{ matrix.arch }}.dll
        asset_content_type: application/octet-stream
