name: Sync with Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # 每天0点运行一次
  workflow_dispatch:  # 手动触发工作流

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout self repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config --global user.email "your-email@example.com"
        git config --global user.name "your-username"

    - name: Add upstream repository
      run: |
        git remote add upstream https://github.com/Bush2021/chrome_plus.git
        git fetch upstream

    - name: Checkout main branch
      run: |
        git checkout main

    - name: Merge upstream changes
      run: |
        git merge upstream/main --allow-unrelated-histories || echo "Merge conflict"
    
    - name: Handle Merge Conflicts
      if: failure()  # 只在合并失败时运行此步骤
      run: |
        echo "Merge conflicts detected. Please resolve the conflicts manually."
        git status
        git diff > conflict_diff.txt
        cat conflict_diff.txt
        exit 1

    - name: Push changes
      if: success()
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git push https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git main

    - name: Upload conflict details
      if: failure()  # 只在合并失败时运行此步骤
      uses: actions/upload-artifact@v2
      with:
        name: conflict_diff
        path: conflict_diff.txt
